// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxvbaefrszosyqiuoyan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dmJhZWZyc3pvc3lxaXVveWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODczODAsImV4cCI6MjA2NjM2MzM4MH0.9ZFie6mdDLW1xKAMRVXBRqf0qWa0K4NKxhIZplCyfHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);